version: "3.8"

services:
  postgresql-db:
    image: postgres
    container_name: postgresql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=63910
      - POSTGRES_DB=rungroop
#    ports:
#      - '5432:5432'
    expose:
      - 5432:5432

  app:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8080:8080'

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://host.docker.internal:5432/rungroop",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "63910",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

    depends_on:
      - postgresql-db
